"""Compile one canonical file into each consumption surface.

Surfaces:
  skill        ~/.claude/skills/<id>/SKILL.md -- gives BOTH /<id> and
               model-invocation. Claude Code merged custom commands into
               skills, so these are one artifact, not two. .claude/commands/
               still works but is the legacy format.
  instructions build/instructions/<id>.md -- paste into a claude.ai Project's
               "Custom instructions" box. Flat, no frontmatter.
  knowledge    build/knowledge/<id>.md -- upload as a Project knowledge file.
  cli          rendered to stdout / pbcopy by `prompt fill`.

Install writes a managed marker so a hand-edit in ~/.claude is detected
rather than silently destroyed. See MARKER_RX.

Targets Python 3.9. Stdlib only.
"""

import datetime
import hashlib
import re
from typing import Dict, List, Optional, Tuple

from . import frontmatter as FM
from . import template as T

SURFACES = ("skill", "instructions", "knowledge", "cli")

MARKER_PREFIX = "<!-- prompt-library:managed"
MARKER_RX = re.compile(
    r"^<!-- prompt-library:managed id=(?P<id>\S+) surface=(?P<surface>\S+) "
    r"content-sha256=(?P<sha>[0-9a-f]{64}) built=(?P<built>\S+) -->$",
    re.MULTILINE)

# Canonical keys that are ours, not Claude Code's -- never passed through.
_OURS = {"id", "kind", "status", "surfaces", "vars", "source", "reference",
         "title"}


def content_sha(text: str) -> str:
    """Hash of the content with any managed marker line removed.

    Must exclude the marker, or the hash could never match what it records.
    """
    stripped = MARKER_RX.sub("", text).rstrip() + "\n"
    return hashlib.sha256(stripped.encode("utf-8")).hexdigest()


def add_marker(text: str, prompt_id: str, surface: str) -> str:
    body = MARKER_RX.sub("", text).rstrip() + "\n"
    return "%s\n%s id=%s surface=%s content-sha256=%s built=%s -->\n" % (
        body, MARKER_PREFIX, prompt_id, surface, content_sha(body),
        datetime.datetime.now().replace(microsecond=0).isoformat())


def read_marker(text: str) -> Optional[re.Match]:
    return MARKER_RX.search(text)


def skill_values(meta: dict, values: Dict[str, str]) -> Dict[str, str]:
    """For the skill surface, `from-arg` vars become $argname placeholders so
    the value arrives at invocation time instead of being frozen at build."""
    out = dict(values)
    for v in (meta.get("vars") or []):
        if isinstance(v, dict) and v.get("from-arg"):
            out[v["name"]] = "$" + str(v["from-arg"])
    return out


def _reference_pointer(meta: dict) -> str:
    ref = meta.get("reference")
    if not ref:
        return ""
    return ("Reference the project knowledge file `%s` for all queries, field "
            "mappings and rules. Do not re-derive them.\n\n" % ref)


def emit_skill(meta: dict, body: str, values: Dict[str, str],
               prompt_id: str) -> Tuple[str, List[str]]:
    fmatter = {"name": prompt_id,
               "description": meta.get("description") or meta.get("title") or ""}
    for key in ("when_to_use", "argument-hint", "arguments", "allowed-tools",
                "disallowed-tools", "model", "effort", "paths",
                "disable-model-invocation", "user-invocable"):
        if meta.get(key) is not None:
            fmatter[key] = meta[key]
    rendered, missing = T.render(_reference_pointer(meta) + body,
                                skill_values(meta, values))
    return FM.emit(fmatter) + "\n" + rendered.lstrip("\n"), missing


def emit_instructions(meta: dict, body: str, values: Dict[str, str],
                      prompt_id: str) -> Tuple[str, List[str]]:
    header = (
        "<!-- %s -- generated by ./bin/prompt build. Paste into a claude.ai\n"
        "     Project > Settings > Custom instructions. Do not edit here;\n"
        "     edit prompts/%s.md and rebuild. -->\n\n"
        % (meta.get("title") or prompt_id, prompt_id))
    rendered, missing = T.render(_reference_pointer(meta) + body, values)
    return header + rendered.lstrip("\n"), missing


def emit_knowledge(meta: dict, body: str, values: Dict[str, str],
                   prompt_id: str) -> Tuple[str, List[str]]:
    title = meta.get("title") or prompt_id
    rendered, missing = T.render(body, values)
    head = rendered.lstrip("\n")
    if not head.startswith("# "):
        head = "# %s\n\n%s" % (title, head)
    return head, missing


EMITTERS = {"skill": emit_skill,
            "instructions": emit_instructions,
            "knowledge": emit_knowledge}
